# Brooks Tawil
# ECE: 445 Machine Learning for Engineers
## Mini Jupyter Exercise 2

In [1]:
import matplotlib
import numpy as np
import mpl_toolkits.mplot3d

### Synthetic Data
Create a matrix A ∈ R
3×2 whose individual entries are drawn from a Gaussian distribution with mean
0 and variance 1 in an independent and identically distributed (iid) fashion. Once generated, this
matrix should not be changed for the rest of this exercise

In [2]:
mean = 0
variance = 1
ADimensions = (3, 2)
A = np.random.normal(mean, variance, ADimensions)
print (A)
print ("A has rank: " + str(np.linalg.matrix_rank(A)))

[[-0.77029054 -1.59395621]
 [-0.03972249 -0.15418255]
 [-1.1041034  -0.64686915]]
A has rank: 2


### Generation of Dataset #1
Each of our data sample $x ∈ R^3$
is going to be generated in the following fashion: $x = Av$, where
$v ∈ R^2$ is a random vector whose entries are iid Gaussian with mean 0 and variance 1. Note that we will have a different $v$ for each new data sample (i.e., unlike A, it is not fixed for each data sample).

In [3]:
# V is a 2x1 vector, while A is a 3x2 matrix
# We need a 3x500 empty matrix to store all of these 500 data samples
vDimensions = (2, 1)
X = np.array(np.zeros((3,500)))

# Multiply A and v_i, store result in the large data matrix X
for i in range(500):
    v_i = np.random.normal(mean, variance, vDimensions)
    x = np.matmul(A, v_i)
    for j in range(3):
        X[j,i] = x[j]

print ("X is of dimensions: " + str(X.shape))
print (X)

X is of dimensions: (3, 500)
[[ 0.3615011  -0.39714128 -2.23845381 ...  2.43344373  0.48221167
   0.15710865]
 [ 0.00288751 -0.01428247 -0.15117675 ...  0.22413206 -0.02556443
  -0.03680563]
 [ 0.87661455 -0.71025254 -2.39524894 ...  1.2436049   1.83862031
   1.24695087]]


The rank of the matrix resulting from multiplying A and V is equal to 2. The rank of the resulting matrix is bounded by the minimum of the ranks of the matrices A and V. This is becuase the linear transformation of these matrices cannot increase the dimensions of result.

In [4]:
print ("X has rank: " + str(np.linalg.matrix_rank(X)))

X has rank: 2


### Singular Value and Eigenvalue Decomposition of Dataset #1
1. Compute the singular value decomposition of X and the eigenvalue decomposition of $XX^T$

In [5]:
u, s, v = np.linalg.svd(X)
w, v = np.linalg.eig(np.matmul(X, np.matrix.transpose(X)))

The columns of $U$ for mthe left singular values of X. We can correspond these to the eignevectors of $XX^T$. The singular values of $X$ are the square roots of the eigenvalues of $XX^T$ as shown below:

In [6]:
print ("S: " + str(s))
print ("W: " + str(w))
print ("SQRT(W): " + str(np.sqrt(w)))

S: [4.69403497e+01 1.29512543e+01 1.17482077e-15]
W: [2.20339643e+03 1.67734987e+02 1.24346750e-14]
SQRT(W): [4.69403497e+01 1.29512543e+01 1.11510874e-07]


Additionally, the energy in $X$, defined by $||X||^2_F$, is equal to the sum of the squares of the singular values of X, as shown below:

In [7]:
print ("Sum of squares of S: " + str(np.sum(np.square(s))))
print ("Energy of X: " + str(np.sum(np.square(X))))

Sum of squares of S: 2371.131415972691
Energy of X: 2371.131415972689


2. Since the rank of X is 2, it means that the entire dataset spans only a two-dimensional space in $R^3$

In [8]:
print ("S: " + str(s))

S: [4.69403497e+01 1.29512543e+01 1.17482077e-15]


We can see that, eventhough we expect to have 2 non-zero values in S with the third value being zero. Yet our third value, while extremely small, is not exactly equal to zero. That may be happening due to the underlying nature of floating point operations. A representation of a floating point number may lead to small errors that result from computations.

There is a relationship between the two largest singular values of X and the columns of A, and that is the fact that the sequence of singular values is unique. If the singular values are all distinct, then the sequence of singular vectors is unique also. However, when some set of singular values are equal, the corresponding singular vectors span some subspace.

### PCA of Dataset #1 
1. Since each data sample $x_i$ lies in a three-dimensional space, we can have up to three principal components of this data. However, based on your knowledge of how the data was created (and subsequent discussion above), how many principal components should be enough to capture all variation in the data? Justify
your answer as much as you can.

Based off of the previous work and the generation of the data, we should only need 2 principal components in order to capture the variation in the data. 

2. While mean centering is an important preprocessing step for PCA, we do not necessarily need to carry
out mean centering in this problem since the mean vector will have small entries. Indeed, if we let x1,
x2, and x3 denote the first, second, and third component of the random vector x then it follows that
E[xk] = 0, k = 1, 2, 3.

In [9]:
print (X[:,0])

[0.3615011  0.00288751 0.87661455]


In [10]:
m = np.array(np.zeros((1,500)))

# Take the mean of the columns of X
print (np.mean(X, 1))

[-0.07280607 -0.0072305  -0.025269  ]


The entries in the above computation are indeed small and mean centering is not necessarily needed in this case.

In [11]:
# To calculate PCA we need the covariance matrix of X
# Then we compute the eigendecomp of the covariance matrix

covariance_x = np.cov(X)
cov_x_U, cov_x_S, cov_x_V = np.linalg.svd(covariance_x)

print ("The eigenvalues of the covariance matrix (U_m): \n" + str(cov_x_U))

# From here we must select a certain amopunt of principal components with which to do the transformation.
# The problem specifies to select the largest 2 thus we will take the 2 largest columns from the eigenvector matrix

cov_x_U_reduced = np.array([cov_x_U[:,0],cov_x_U[:,1]]).transpose()

print ("The top 2 principal components (U_k): \n" + str(cov_x_U_reduced))

# With the reduced U matrix we can project our original data, X, onto a

The eigenvalues of the covariance matrix (U_m): 
[[-0.8240016  -0.55505918 -0.11371312]
 [-0.06968948 -0.09988543  0.99255543]
 [-0.56228529  0.82579187  0.04362396]]
The top 2 principal components (U_k): 
[[-0.8240016  -0.55505918]
 [-0.06968948 -0.09988543]
 [-0.56228529  0.82579187]]


In [12]:
feature_matrix = np.matmul(cov_x_U_reduced.transpose(), X)

# By multiplying the top 2 principal components we have successfully projected the data.
# The dimensions of 
print (feature_matrix.shape)

(2, 500)


Reconstruct (approximate) the original data samples $x_i$ from the PCA feature vectors.

We simply take our feature matrix, and multiply by the original principal components.

In [13]:
orignal_data = np.matmul(cov_x_U_reduced, feature_matrix)
print (orignal_data.shape)

(3, 500)


The representation error between the actual data and the reformed data can be calculated: